### ISSUE TITLE
game encounters error the second neutronium is destroyed

### ISSUE THREAD

**Issue by Onzeoo** [modo-lv/oni-mod-demolish-neutronium#3]
InvalidOperationException: Sequence contains no matching element

System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
DemolishNeutronium.Extensions.ElementExtensions.FindNeutroniumDust (System.Collections.Generic.IEnumerable`1[T] elements) (at <9a422984170844aa995cdba9e7617bf0>:0)
DemolishNeutronium.MainMod+<>c.<.cctor>b__10_0 () (at <9a422984170844aa995cdba9e7617bf0>:0)
System.Lazy`1[T].CreateValue () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Lazy`1[T].LazyInitValue () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Lazy`1[T].get_Value () (at <695d1cc93cca45069c528c15c9fdd749>:0)
DemolishNeutronium.MainMod.OnDigComplete (System.Single& mass, System.UInt16& element_idx) (at <9a422984170844aa995cdba9e7617bf0>:0)
(wrapper dynamic-method) WorldDamage.WorldDamage.OnDigComplete_Patch1(WorldDamage,int,single,single,uint16,byte,int)
Game.StepTheSim (System.Single dt) (at <ad882e55d8ac49379773540ee16f428f>:0)
Game.UnsafeSim200ms (System.Single dt) (at <ad882e55d8ac49379773540ee16f428f>:0)
Game.SimEveryTick (System.Single dt) (at <ad882e55d8ac49379773540ee16f428f>:0)
Game.Update () (at <ad882e55d8ac49379773540ee16f428f>:0)

Build: U48-568201-V

Particles off in config. 
other mods are bigger capacity, build over plants, bigger camera zoom out, airlock door, mod updater, infinite gases and liquids, customizable speed, gas overlay

**Comment by pixelkritzel** [comment]
I had the same error in the base game.

**Comment by modo-lv** [comment]
My bad, I forgot to re-test without Rocketry Expanded before release. Should be fixed in v1.1.1.

**Comment by modo-lv** [comment]
Fixed in 1.1.1.
